config/routes.rb
Gestimepro3::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "tareas#index"

  resources :users
  match "users/create" => "users#create", :as => "users", :via => :post
  match "users" => "users#index", :as => "users", :via => :get

  resources :sessions
  match "sessions/create" => "sessions#create", :as => "sessions"

  resources :tareas

  resources :proyectos

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base

  validates :nombre, :presence => true, :uniqueness => true


  has_many :tareas



  def horas_totales
    @horas_totales = 0.00
    self.tareas.each do |tarea|
      @horas_totales += tarea.total
    end
    @horas_totales
  end
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_filter :is_admin
  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyectos }
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
    @proyecto = Proyecto.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/new
  # GET /proyectos/new.json
  def new
    @proyecto = Proyecto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/1/edit
  def edit
    @proyecto = Proyecto.find(params[:id])
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(params[:proyecto])

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to proyectos_url, notice: 'Proyecto fue creado correctamente.' }
        format.json { render json: @proyecto, status: :created, location: @proyecto }
      else
        format.html { render action: "new" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyectos/1
  # PUT /proyectos/1.json
  def update
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      if @proyecto.update_attributes(params[:proyecto])
        format.html { redirect_to @proyecto, notice: 'Proyecto fue actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto = Proyecto.find(params[:id])
    @proyecto.destroy

    respond_to do |format|
      format.html { redirect_to proyectos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/proyectos/_form.html.erb
<hr>
<%= form_for(@proyecto) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %>Formulario invalido:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
    <hr>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Mostrar', @proyecto %></li>
        <li><%= link_to 'Proyectos', proyectos_path %>
      </li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Editar proyecto</h1>

  <%= render 'form' %>

</section>

app/views/proyectos/index.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Nuevo Proyecto', new_proyecto_path %> </li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Proyectos</h1>
  <hr>

  <article>
  <div id="demo_jui">
    <table class="display" id="example" >
      <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Acciones</th>
      </tr>
      </thead>
      <tbody>
      <% @proyectos.each do |proyecto| %>
          <tr>
            <td><%= proyecto.nombre %></td>
            <td><%= proyecto.descripcion %></td>
            <td><%= link_to 'Mostrar', proyecto %> |
            <%= link_to 'Editar', edit_proyecto_path(proyecto) %>
            <% link_to 'Destroy', proyecto, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
      <% end %>

      </tbody>
    </table>
  </div>

  </article>
</section>

app/views/proyectos/new.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Volver', proyectos_path %></li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Nuevo proyecto</h1>

  <%= render 'form' %>

</section>

app/views/proyectos/show.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Editar', edit_proyecto_path(@proyecto) %> </li>
      <li><%= link_to 'Volver', proyectos_path %></li>
    </ul>
  </nav>
</div>



<section class="content">


  <h1>Detalle proyecto <%= @proyecto.nombre %></h1>
                  <hr>

  <article>
  <p>
    <b>Descripcion:</b>
    <%= @proyecto.descripcion %>
  </p>
  <p>
    <b>Horas totales:</b>
    <%= @proyecto.horas_totales %>
  </p>
  </article>
                <hr>

  <article>
  <h2>Tareas</h2>


    <div id="demo_jui">
      <table class="display" id="example" >
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Fecha</th>
          <th>Inicio</th>
          <th>Termino</th>
          <th>Total</th>
          <th>Usuario</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @proyecto.tareas.each do |tarea| %>
            <tr>
              <td><%= tarea.nombre %></td>
              <td><%= tarea.inicio.strftime("%d-%m-%Y") %></td>
              <td><%= tarea.inicio.strftime("%H:%M") %></td>
              <td><%= tarea.termino.strftime("%H:%M") %></td>
              <td><%= tarea.total %></td>
              <td><%= tarea.user.nombre + " " + tarea.user.apellido + " (" << tarea.user.email + ")"    %></td>
              <td><%= link_to 'Mostrar', tarea %></td>
            </tr>
        <% end %>

        </tbody>
      </table>
    </div>

  </article>
</section>