config/routes.rb
Gestimepro3::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "tareas#index"

  resources :users
  match "users/create" => "users#create", :as => "users", :via => :post
  match "users" => "users#index", :as => "users", :via => :get

  resources :sessions
  match "sessions/create" => "sessions#create", :as => "sessions"

  resources :tareas

  resources :proyectos

end

app/models/tarea.rb
require "Date"
class Tarea < ActiveRecord::Base
  belongs_to :proyecto
  belongs_to :user
  before_validation :set_dates



  attr_accessor :fecha, :hora_inicio, :hora_termino, :total

  validates :proyecto_id,
            :presence => true

  validates :user_id,
            :presence => true

  validates :nombre,
            :presence => true

#  validates :fecha,
#            :presence => true

#  validates :hora_inicio,
#            :presence => true

#  validates :hora_termino,
#            :presence => true

  validates :inicio,
            :presence => true

  validates :termino,
            :presence => true




  def fecha
    if inicio
       self.fecha = self.inicio.strftime("%d/%m/%Y")
    else if termino
          self.fecha = self.termino.strftime("%d/%m/%Y")
         end
    end
  end

  def hora_inicio
    if inicio
      self.hora_inicio = self.inicio.strftime("%H:%M")
    end
  end

  def hora_termino
    if termino
      self.hora_termino = self.termino.strftime("%H:%M")
    end

  end


  def set_dates
    if @fecha.strip != "" && @hora_inicio.strip != ""
     self.inicio = DateTime.strptime(@fecha.to_s + " " + @hora_inicio.to_s,"%d/%m/%Y %H:%M" )
    end
    if @fecha.strip != "" && @hora_termino.strip != ""
     self.termino = DateTime.strptime(@fecha.to_s + " " + @hora_termino.to_s,"%d/%m/%Y %H:%M" )

    end

  end

  def total
    (self.termino - self.inicio) / 3600
  end


end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  # GET /tareas
  # GET /tareas.json
  def index
    @tareas = Tarea.find_all_by_user_id(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tareas }
    end
  end

  # GET /tareas/1
  # GET /tareas/1.json
  def show
    @tarea = Tarea.find(params[:id])
    print @tarea.user.nombre

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tarea }
    end
  end

  # GET /tareas/new
  # GET /tareas/new.json
  def new
    @tarea = Tarea.new
    @proyectos = Proyecto.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tarea }
    end
  end

  # GET /tareas/1/edit
  def edit
    @tarea = Tarea.find(params[:id])
    print @tarea.hora_inicio
    @proyectos = Proyecto.all
  end

  # POST /tareas
  # POST /tareas.json
  def create
    @tarea = Tarea.new(params[:tarea])
    @tarea.user_id = session[:user_id]
    print @tarea.hora_termino


    if @tarea.save
      redirect_to @tarea, notice: 'Tarea fue creada!'
    else
      @proyectos = Proyecto.all
      render action: "new"
    end
  end

  # PUT /tareas/1
  # PUT /tareas/1.json
  def update
    @tarea = Tarea.find(params[:id])

    respond_to do |format|
      if @tarea.update_attributes(params[:tarea])
        format.html { redirect_to @tarea, notice: 'Tarea fue actualizada!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1
  # DELETE /tareas/1.json
  def destroy
    @tarea = Tarea.find(params[:id])
    @tarea.destroy

    respond_to do |format|
      format.html { redirect_to tareas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/tareas/_form.html.erb
<hr>
<%= form_for(@tarea) do |f| %>
  <% if @tarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tarea.errors.count, "error") %>Formulario invalido</h2>

      <ul>
      <% @tarea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
        <hr>
  <% end %>


    <div class="field">
      <%= f.label :proyecto %><br />
      <%= f.select :proyecto_id , @proyectos.map {|u| [u.nombre,u.id]},  {:include_blank => 'Seleccione un proyecto'} %>
    </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
    <hr>
    <div class="field">
      <%= f.label :fecha %><br />
      <%= f.text_field :fecha , :class => "datepicker"%>
    </div>
  <div class="field">
    <%= f.label :hora_inicio %><br />
    <%= f.text_field :hora_inicio , :class => "timepicker"%>
  </div>
  <div class="field">
    <%= f.label :hora_termino %><br />
    <%= f.text_field :hora_termino , :class => "timepicker"%>
  </div>
    <hr>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tareas/edit.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Detalle', @tarea %> </li>
        <li><%= link_to 'Tareas', tareas_path %>
      </li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Editar tarea</h1>

  <%= render 'form' %>

</section>

app/views/tareas/index.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Nueva Tarea', new_tarea_path %></li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Tareas realizadas</h1>
  <hr>

  <article>
    <div id="demo_jui">
      <table class="display" id="example" >
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Fecha</th>
          <th>Inicio</th>
          <th>Termino</th>
          <th>Total</th>
          <th>Proyecto</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>

        <% @tareas.each do |tarea| %>
            <tr>
              <td><%= tarea.nombre %></td>
              <td><%= tarea.inicio.strftime("%d-%m-%Y") %></td>
              <td><%= tarea.inicio.strftime("%H:%M") %></td>
              <td><%= tarea.termino.strftime("%H:%M") %></td>
              <td><%= tarea.total %></td>
              <td><%= tarea.proyecto.nombre   %></td>
              <td><%= link_to 'Mostrar', tarea %> |
                <%= link_to 'Editar', edit_tarea_path(tarea) %>
                <% link_to 'Destroy', tarea, confirm: 'Are you sure?', method: :delete %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </article>
</section>

app/views/tareas/new.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Volver', tareas_path %></li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Nueva tarea</h1>

  <%= render 'form' %>

</section>

app/views/tareas/show.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Nueva Tarea', new_tarea_path %></li>
      <li><%= link_to 'Editar', edit_tarea_path(@tarea) %></li>
      <li><%= link_to 'Tareas', tareas_path %></li>
    </ul>
  </nav>
</div>



<section class="content">


  <h1>Detalle tarea <%= @tarea.nombre %></h1>
  <hr>

  <article>

    <p>
      <b>Proyecto:</b>
      <%= @tarea.proyecto.nombre %>
    </p>
    <p>
      <b>Descripcion:</b>
      <%= @tarea.descripcion %>
    </p>

    <p>
      <b>Fecha:</b>
      <%= @tarea.inicio.strftime("%d-%m-%Y") %>
    </p>
    <p>
      <b>Inicio:</b>
      <%= @tarea.inicio.strftime("%H:%M") %>
    </p>

    <p>
      <b>Termino:</b>
      <%= @tarea.termino.strftime("%H:%M") %>



    <p>
      <b>Total:</b>
      <%= @tarea.total %>
    </p>
    <p>
      <b>Usuario:</b>
      <%= @tarea.user.email %>
    </p>
  </article>
</section>