config/routes.rb
Gestimepro3::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "tareas#index"

  resources :users
  match "users/create" => "users#create", :as => "users", :via => :post
  match "users" => "users#index", :as => "users", :via => :get

  resources :sessions
  match "sessions/create" => "sessions#create", :as => "sessions"

  resources :tareas

  resources :proyectos

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  attr_accessible :email, :password, :password_confirmation, :nombre, :apellido, :admin

  #validates_confirmation_of :password
  #validates_presence_of :password, :on => :create
  #validates_presence_of :email
  #validates_uniqueness_of :email


  validates :email,
            :presence => true,
            :uniqueness => { :case_sensitive => false },
            :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}



  validates :password,
            :confirmation => true,
            :presence => {
                :on => :create
            }

  validates :nombre,
            :presence => true


  has_many :tareas

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :is_admin
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  # GET /proyectos/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def update
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario fue actualizado!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def show
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :nombre %><br />
      <%= f.text_field :nombre %>
    </p>
    <p>
      <%= f.label :apellido %><br />
      <%= f.text_field :apellido %>
    </p>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :password %>
    <p>
      <%= f.label :admin %><br />
      <%= f.check_box :admin %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/index.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Nuevo Usuario', sign_up_path %></li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Usuarios</h1>
  <hr>

  <article>
    <div id="demo_jui">
      <table class="display" id="example" >
        <thead>
        <tr>
          <th>Email</th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>admin</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |usuario| %>
            <tr>
              <td><%= usuario.email %></td>
              <td><%= usuario.nombre %></td>
              <td><%= usuario.apellido %></td>
              <td><%= usuario.admin %></td>
              <td><%= link_to 'Mostrar', usuario %>
                <% link_to 'Editar', edit_user_path(usuario) %>
                <% link_to 'Destroy', usuario, confirm: 'Are you sure?', method: :delete %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </article>
</section>

app/views/users/new.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Volver', users_path %></li>
    </ul>
  </nav>
</div>



<section class="content">

  <h1>Sign Up</h1>
  <hr>

  <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Formulario es invalido</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <p>
        <%= f.label :nombre %><br />
        <%= f.text_field :nombre %>
      </p>
      <p>
        <%= f.label :apellido %><br />
        <%= f.text_field :apellido %>
      </p>
      <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation %>  <br />
        <%= f.password_field :password_confirmation %>
      </p>
      <p>
        <%= f.label :admin %><br />
        <%= f.check_box :admin %>
      </p>
      <hr>
      <p class="button"><%= f.submit %></p>
  <% end %>


</section>

app/views/users/show.html.erb
<div class="sidebar2">
  <nav>
    <ul>
      <li><%= link_to 'Volver', users_path %></li>
    </ul>
  </nav>
</div>



<section class="content">


  <h1>Detalle de <%= @user.nombre.to_s + " " + @user.apellido.to_s + " (" + @user.email.to_s + ")"  %></h1>

  <hr>
  <article>
  <h2>Tareas</h2>


  <div id="demo_jui">
    <table class="display" id="example" >
      <thead>
      <tr>

        <th>Nombre</th>
        <th>Fecha</th>
        <th>Inicio</th>
        <th>Termino</th>
        <th>Total</th>
        <th>Proyecto</th>
        <th>Acciones</th>
      </tr>
      </thead>
      <tbody>
      <% @user.tareas.each do |tarea| %>
          <tr>
            <td><%= tarea.nombre %></td>
            <td><%= tarea.inicio.strftime("%d-%m-%Y") %></td>
            <td><%= tarea.inicio.strftime("%H:%M") %></td>
            <td><%= tarea.termino.strftime("%H:%M") %></td>
            <td><%= tarea.total %></td>
            <td><%= tarea.proyecto.nombre   %></td>
            <td><%= link_to 'Mostrar ', tarea %>
              <% link_to 'Editar', edit_tarea_path(tarea) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  </article>
</section>