config/routes.rb
Gestimepro3::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "tareas#index"

  resources :users
  match "users/create" => "users#create", :as => "users", :via => :post
  match "users" => "users#index", :as => "users", :via => :get

  resources :sessions
  match "sessions/create" => "sessions#create", :as => "sessions"

  resources :tareas

  resources :proyectos

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gestimepro</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag :jui %>
  <%= javascript_include_tag :dt %>
  <%= csrf_meta_tag %>







  <script>

      $(document).ready(function() {

          oTable = $('#example').dataTable({
              "bJQueryUI": true,
              "sPaginationType": "full_numbers"
          });

          $(".datepicker").datepicker({
              showAnim: 'fadeIn'
          });
          $(".timepicker").timepicker({
              showAnim: 'fadeIn'
          });

      });

      (function($) {
          $.timepicker.regional['es'] = {
              timeOnlyTitle: 'Elegir una hora',
              timeText: 'Hora',
              hourText: 'Horas',
              minuteText: 'Minutos',
              secondText: 'Segundos',
              millisecText: 'Milisegundos',
              timezoneText: 'Huso horario',
              currentText: 'Ahora',
              closeText: 'Cerrar',
              timeFormat: 'hh:mm',
              amNames: ['a.m.', 'AM', 'A'],
              pmNames: ['p.m.', 'PM', 'P'],
              ampm: false
          };
          $.timepicker.setDefaults($.timepicker.regional['es']);
      }) (jQuery);

      jQuery(function($){
          $.datepicker.regional['es'] = {
              closeText: 'Cerrar',
              prevText: '&#x3c;Ant',
              nextText: 'Sig&#x3e;',
              currentText: 'Hoy',
              monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
                  'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
              monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun',
                  'Jul','Ago','Sep','Oct','Nov','Dic'],
              dayNames: ['Domingo','Lunes','Martes','Mi&eacute;rcoles','Jueves','Viernes','S&aacute;bado'],
              dayNamesShort: ['Dom','Lun','Mar','Mi&eacute;','Juv','Vie','S&aacute;b'],
              dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','S&aacute;'],
              weekHeader: 'Sm',
              dateFormat: 'dd/mm/yy',
              firstDay: 1,
              isRTL: false,
              showMonthAfterYear: false,
              yearSuffix: ''};
          $.datepicker.setDefaults($.datepicker.regional['es']);
      });

  </script>




</head>
<body>



<header>
  <h4 id="letraTitulo">GesTimePro</h4>

  <% if current_user %>
  <h3 id="letraNombre"><%= current_user.nombre + " " + current_user.apellido + " ("+ current_user.email + ")" %></h3>
  <% end %>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash#{name}", :class =>"ui-state-highlight" %>
  <% end %>
</header>


<div class="contenedorGeneral">

<% if current_user %>
<div class="sidebar1">
  <nav>
    <ul>
      <li> <%= link_to "Tareas", tareas_path %></li>

      <% if current_user.admin? %>
      <li><%= link_to "Proyectos", proyectos_path %></li>
      <li><%= link_to "Usuarios", users_path %></li>
      <% end %>
      <li><%= link_to "Salir", log_out_path %></li>

    </ul>
  </nav>
  <div class="clear"></div>

</div>



<% end %>







  <%= yield %>

  <div class="clear"></div>
</div>

<a id="html5logo" href="http://www.w3.org/html/logo/">
  <img src="http://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png" width="165" height="64" alt="HTML5 Powered with CSS3 / Styling, and Semantics" title="HTML5 Powered with CSS3 / Styling, and Semantics">
</a>



</body>
</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gestimepro</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag :jui %>
  <%= csrf_meta_tag %>




</head>
<body>



<header>
  <h4 id="letraTitulo">GesTimePro</h4>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash#{name}", :class =>"ui-state-highlight" %>
  <% end %>
</header>


<div class="contenedorGeneral">
               <section class="content">
  <%= yield %>
               </section>
  <div class="clear"></div>
</div>

<a id="html5logo" href="http://www.w3.org/html/logo/">
  <img src="http://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png" width="165" height="64" alt="HTML5 Powered with CSS3 / Styling, and Semantics" title="HTML5 Powered with CSS3 / Styling, and Semantics">
</a>



</body>
</html>